# Generated by Django 4.2.1 on 2023-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-time_created',), 'verbose_name': 'Новости мира', 'verbose_name_plural': 'Новости мира'},
        ),
    ]
